### ISSUE TITLE
"fatal error: runtime: stack growth during syscall" when pressing PTT button

### ISSUE THREAD

**Issue by MarcusWolschon** [MarcusWolschon/RasPi_stage_intercom#9]
After doing an "apt-get dist upgrade" on Raspian (still using an ancient Go 1.3),
every press of the Push To Talk button produces:

`Connected to 192.168.1.1:64738 (0)
Welcome message:
Welcome to this server running Murmur.
Enjoy your stay!

Unable to find channel: talkiepi
Channel 'Root' has 2 participants
Button is pressed
fatal error: runtime: stack growth during syscall

runtime stack:
runtime.throw(0x4375a0)
        /usr/lib/go/src/pkg/runtime/panic.c:520 +0x5c
runtime.newstack()
        /usr/lib/go/src/pkg/runtime/stack.c:739 +0x6d0
runtime.morestack()
        /usr/lib/go/src/pkg/runtime/asm_arm.s:210 +0x44

goroutine 25 [stack growth]:
runtime.cgocall(0x14960, 0x461a2ee8)
        /usr/lib/go/src/pkg/runtime/cgocall.c:142 +0xdc fp=0x461a2ed8 sp=0x461a2eac
github.com/dchote/go-openal/openal._Cfunc_alcCaptureSamples(0x0, 0x56d05000, 0x1e0)
        github.com/dchote/go-openal/openal/_obj/_cgo_defun.c:297 +0x34 fp=0x461a2ee4 sp=0x461a2ed8
github.com/dchote/go-openal/openal.(*CaptureDevice).CaptureTo(0x56cc42a0, 0x56d05000, 0x3c0, 0x3c0)
        /home/mumble/gocode/src/github.com/dchote/go-openal/openal/alcCore.go:172 +0x80 fp=0x461a2ef4 sp=0x461a2ee4
github.com/dchote/go-openal/openal.(*CaptureDevice).CaptureSamples(0x56cc42a0, 0x1e0, 0x56d05000, 0x3c0, 0x3c0)
        /home/mumble/gocode/src/github.com/dchote/go-openal/openal/alcCore.go:197 +0xa4 fp=0x461a2f20 sp=0x461a2ef4
github.com/dchote/gumble/gumbleopenal.(*Stream).sourceRoutine(0x56d7e1e0)
        /home/mumble/gocode/src/github.com/dchote/gumble/gumbleopenal/stream.go:140 +0x22c fp=0x461a2fc4 sp=0x461a2f20
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445 fp=0x461a2fc4 sp=0x461a2fc4
created by github.com/dchote/gumble/gumbleopenal.(*Stream).StartSource
        /home/mumble/gocode/src/github.com/dchote/gumble/gumbleopenal/stream.go:66 +0xb0

goroutine 16 [chan receive]:
github.com/dchote/talkiepi.(*Talkiepi).Init(0x56d8e000)
        /home/mumble/gocode/src/github.com/dchote/talkiepi/client.go:28 +0xfc
main.main()
        /home/mumble/gocode/src/github.com/MarcusWolschon/RasPi_stage_intercom/cmd/talkiepi/main.go:62 +0x9b8

goroutine 19 [finalizer wait]:
runtime.park(0x2b2f0, 0x44a318, 0x4382a9)
        /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x5c
runtime.parkunlock(0x44a318, 0x4382a9)
        /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x40
runfinq()
        /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xa0
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 21 [sleep]:
time.Sleep(0x1dcd6500, 0x0)
        /usr/lib/go/src/pkg/runtime/time.goc:39 +0x3c
github.com/dchote/talkiepi.func·002()
        /home/mumble/gocode/src/github.com/dchote/talkiepi/gpio.go:47 +0x110
created by github.com/dchote/talkiepi.(*Talkiepi).initGPIO
        /home/mumble/gocode/src/github.com/dchote/talkiepi/gpio.go:49 +0x1a4

goroutine 22 [IO wait]:
net.runtime_pollWait(0x46b94918, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:146 +0x6c
net.(*pollDesc).Wait(0x56cf54f8, 0x72, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:84 +0x44
net.(*pollDesc).WaitRead(0x56cf54f8, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).Read(0x56cf54c0, 0x56d04c00, 0x400, 0x400, 0x0, 0x46b93248, 0xb)
        /usr/lib/go/src/pkg/net/fd_unix.go:242 +0x320
net.(*conn).Read(0x56cc44c8, 0x56d04c00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/net.go:122 +0xd4
crypto/tls.(*block).readFromUntil(0x56ce7620, 0x46b949a0, 0x56cc44c8, 0x5, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:451 +0xdc
crypto/tls.(*Conn).readRecord(0x56d5e300, 0x17, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:536 +0x1b4
crypto/tls.(*Conn).Read(0x56d5e300, 0x56d00900, 0x6, 0x6, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:901 +0x16c
io.ReadAtLeast(0x46b94d68, 0x56d5e300, 0x56d00900, 0x6, 0x6, 0x6, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/io/io.go:289 +0xf4
io.ReadFull(0x46b94d68, 0x56d5e300, 0x56d00900, 0x6, 0x6, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/io/io.go:307 +0x6c
github.com/dchote/gumble/gumble.(*Conn).ReadPacket(0x56cd2960, 0x56cc9020, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/conn.go:46 +0x15c
github.com/dchote/gumble/gumble.(*Client).readRoutine(0x56d4a380)
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:220 +0x5c
created by github.com/dchote/gumble/gumble.DialWithDialer
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:113 +0x298

goroutine 23 [select]:
github.com/dchote/gumble/gumble.(*Client).pingRoutine(0x56d4a380)
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:202 +0x218
created by github.com/dchote/gumble/gumble.DialWithDialer
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:114 +0x2c0

goroutine 17 [syscall]:
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 26 [chan receive]:
github.com/dchote/gumble/gumble.func·001()
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:178 +0x6c
created by github.com/dchote/gumble/gumble.(*Client).AudioOutgoing
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:187 +0xc0
`

**Comment by MarcusWolschon** [comment]
Hopefully an update to Debian strech will do the job.
https://github.com/dchote/talkiepi/blob/master/doc/README.md

**Comment by MarcusWolschon** [comment]
Stitt happens with golang 1.10

`Welcome to this server running Murmur.
Enjoy your stay!

Unable to find channel: talkiepi
Channel 'Root' has no other participants
Button is pressed
fatal error: runtime: stack growth during syscall

runtime stack:
runtime.throw(0x4375a0)
        /usr/lib/go/src/pkg/runtime/panic.c:520 +0x5c
runtime.newstack()
        /usr/lib/go/src/pkg/runtime/stack.c:739 +0x6d0
runtime.morestack()
        /usr/lib/go/src/pkg/runtime/asm_arm.s:210 +0x44

goroutine 25 [stack growth]:
runtime.cgocall(0x14960, 0x4619dee8)
        /usr/lib/go/src/pkg/runtime/cgocall.c:142 +0xdc fp=0x4619ded8 sp=0x4619deac
github.com/dchote/go-openal/openal._Cfunc_alcCaptureSamples(0x0, 0x56cff000, 0x1e0)
        github.com/dchote/go-openal/openal/_obj/_cgo_defun.c:297 +0x34 fp=0x4619dee4 sp=0x4619ded8
github.com/dchote/go-openal/openal.(*CaptureDevice).CaptureTo(0x56cbe290, 0x56cff000, 0x3c0, 0x3c0)
        /home/mumble/gocode/src/github.com/dchote/go-openal/openal/alcCore.go:172 +0x80 fp=0x4619def4 sp=0x4619dee4
github.com/dchote/go-openal/openal.(*CaptureDevice).CaptureSamples(0x56cbe290, 0x1e0, 0x56cff000, 0x3c0, 0x3c0)
        /home/mumble/gocode/src/github.com/dchote/go-openal/openal/alcCore.go:197 +0xa4 fp=0x4619df20 sp=0x4619def4
github.com/dchote/gumble/gumbleopenal.(*Stream).sourceRoutine(0x56d7a1a0)
        /home/mumble/gocode/src/github.com/dchote/gumble/gumbleopenal/stream.go:140 +0x22c fp=0x4619dfc4 sp=0x4619df20
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445 fp=0x4619dfc4 sp=0x4619dfc4
created by github.com/dchote/gumble/gumbleopenal.(*Stream).StartSource
        /home/mumble/gocode/src/github.com/dchote/gumble/gumbleopenal/stream.go:66 +0xb0

goroutine 16 [chan receive]:
github.com/dchote/talkiepi.(*Talkiepi).Init(0x56d8a000)
        /home/mumble/gocode/src/github.com/dchote/talkiepi/client.go:28 +0xfc
main.main()
        /home/mumble/gocode/src/github.com/MarcusWolschon/RasPi_stage_intercom/cmd/talkiepi/main.go:62 +0x9b8

goroutine 19 [finalizer wait]:
runtime.park(0x2b2f0, 0x44a318, 0x4382a9)
        /usr/lib/go/src/pkg/runtime/proc.c:1369 +0x5c
runtime.parkunlock(0x44a318, 0x4382a9)
        /usr/lib/go/src/pkg/runtime/proc.c:1385 +0x40
runfinq()
        /usr/lib/go/src/pkg/runtime/mgc0.c:2644 +0xa0
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 21 [sleep]:
time.Sleep(0x1dcd6500, 0x0)
        /usr/lib/go/src/pkg/runtime/time.goc:39 +0x3c
github.com/dchote/talkiepi.func·002()
        /home/mumble/gocode/src/github.com/dchote/talkiepi/gpio.go:47 +0x110
created by github.com/dchote/talkiepi.(*Talkiepi).initGPIO
        /home/mumble/gocode/src/github.com/dchote/talkiepi/gpio.go:49 +0x1a4

goroutine 22 [IO wait]:
net.runtime_pollWait(0x46b8f898, 0x72, 0x0)
        /usr/lib/go/src/pkg/runtime/netpoll.goc:146 +0x6c
net.(*pollDesc).Wait(0x56cef4f8, 0x72, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:84 +0x44
net.(*pollDesc).WaitRead(0x56cef4f8, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/fd_poll_runtime.go:89 +0x40
net.(*netFD).Read(0x56cef4c0, 0x56cfec00, 0x400, 0x400, 0x0, 0x46b8e248, 0xb)
        /usr/lib/go/src/pkg/net/fd_unix.go:242 +0x320
net.(*conn).Read(0x56cbe4c8, 0x56cfec00, 0x400, 0x400, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/net/net.go:122 +0xd4
crypto/tls.(*block).readFromUntil(0x56ce1620, 0x46b8f920, 0x56cbe4c8, 0x5, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:451 +0xdc
crypto/tls.(*Conn).readRecord(0x56d76300, 0x17, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:536 +0x1b4
crypto/tls.(*Conn).Read(0x56d76300, 0x56cfa8f0, 0x6, 0x6, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/crypto/tls/conn.go:901 +0x16c
io.ReadAtLeast(0x46b8fc38, 0x56d76300, 0x56cfa8f0, 0x6, 0x6, 0x6, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/io/io.go:289 +0xf4
io.ReadFull(0x46b8fc38, 0x56d76300, 0x56cfa8f0, 0x6, 0x6, 0x0, 0x0, 0x0)
        /usr/lib/go/src/pkg/io/io.go:307 +0x6c
github.com/dchote/gumble/gumble.(*Conn).ReadPacket(0x56ccc990, 0x56cc2f00, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/conn.go:46 +0x15c
github.com/dchote/gumble/gumble.(*Client).readRoutine(0x56d44380)
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:220 +0x5c
created by github.com/dchote/gumble/gumble.DialWithDialer
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:113 +0x298

goroutine 23 [select]:
github.com/dchote/gumble/gumble.(*Client).pingRoutine(0x56d44380)
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:202 +0x218
created by github.com/dchote/gumble/gumble.DialWithDialer
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:114 +0x2c0

goroutine 17 [syscall]:
runtime.goexit()
        /usr/lib/go/src/pkg/runtime/proc.c:1445

goroutine 26 [chan receive]:
github.com/dchote/gumble/gumble.func·001()
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:178 +0x6c
created by github.com/dchote/gumble/gumble.(*Client).AudioOutgoing
        /home/mumble/gocode/src/github.com/dchote/gumble/gumble/client.go:187 +0xc0
`

**Comment by MarcusWolschon** [comment]
fixed
